### ISSUE TITLE
Aid Data Concessions Geocoding Spec

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/ocds_location_extension#3]
Aid Data have developed a framework for geocoding concessions contracts. It is described as:

> a framework for geo-coding location information found in contracts (particularly extractive concession contracts), such as those published by governments, companies, the Extractive Industries Transparency Initiative (EITI), and third-party databases such as www.resourcecontracts.org and www.openlandcontracts.org. 

> It builds upon AidData’s work in geo-coding 550+ concession licenses in Liberia between 2004-2015 – we leverage lessons learned to construct a standard for geo-coding these contracts that may be adopted by companies, governments, and third-party institutions such as EITI and OCP. Our hope is that such a standard can enable spatial information on open contracts to be transparent, interoperable, and usable by diverse stakeholders.

The framework provides:

> two measures for spatial information that may be standardized across contracts and enable effective identification, interpretation, and use of spatial open contracting data. 

The goal of this is to:

> build upon OCP’s location extension to the OCDS, presenting attributes that can be integrated into the OCDS’s schema and can guide users as to the accuracy, reliability, and utility of the featured spatial information. These measures thus add to, rather than replace, the existing attributes within the location specification of the OCDS.

These two additional measures would apply to **polygons** represented using the existing location GeoJSON geometry fields.

## Source Type

Aid Data propose a measure of the type of source used to provide location information for a given polygon. 

They note that:

> Companies, governments, and third-party institutions publish varying types of location information in contract databases or cadasters, ranging in precision, comprehensiveness, and ease of use. For example, publishers may publish PDF contracts with unstructured coordinate information found in the form of decimal degrees, UTM coordinates, or survey information. Alternatively, publishers with high technical capacity, among other factors, may publish attributes from contracts in a cadastre with accompanying spatial information, featured in GIS-based platforms. These variations in source type are important for two reasons:
> 
> * Confidence: They affect a user’s degree of confidence in the accuracy of the location information.
> * Compliance: They are an indicator of publishers’ standards of reporting and verification.

The suggested values for a ```sourceType``` code are:

Therefore, we propose the following measure for each polygon that represents a contract area:

| Value | Category |
|-------|----------|
| 1 | The polygon is sourced from spatial (digitized) information published by a company, government, or third-party institution. |
| 2 | The polygon is sourced from location information that provides decimal degrees for all vertices of the polygon. |
| 3 | The polygon is sourced from location information that provides UTM coordinates for all vertices of the polygon. |
| 4 | The polygon is sourced from survey-based coordinates that provide the location of all vertices of the polygon. |
| 5 | The polygon is sourced from survey-based coordinates that do not provide the location of all vertices of the polygon. |
| 0 | The location information for a given polygon varies across vertices among the categories presented above. |

### Questions and issues

* In OCDS we usually work with camelCase rather than numeric codelist values. Is there a strong reason to prefer numeric values here? 

* What other standardised methods for polygon provenance exist that we might draw upon?

* Where in the location extension structure should this information be held? 

## Point of Origin

Aid Data propose a code to indicate the nature of the Point of Origin

They state that: 

> This measure is particularly salient for contracts that feature survey-based coordinates for representing the boundaries of a contract area. The clarity of the point of origin is one of the most significant determinants of the quality, accuracy, and difficulty of geo-coding a contract area. Clear starting points – such as coordinates, place names, or clearly-identifiable landmarks – provide reliable indicators of boundaries and enable effective mapping of subsequent points. By contrast, proximate starting points – including references to nearby towns or villages, or environmental landmarks – heighten the risk that a polygon, although it may capture the general shape and form of a contract area, does not accurately represent the true boundaries of the area. In such a case, each point following the starting point, even if it is accurate, would be systematically misrepresented, skewing the representation of the contract area.
Thus, a binary indicator of the exactness or approximate nature of the starting point is a precondition to gauge the accuracy of survey-based coordinates – if the starting point is incorrect or ambiguous, the rest of the polygon is distorted, often to unknowable degrees. 

The proposed values for this field are:

| Value | Category |
|-------|----------|
| 0 | Approximate starting point from survey-based coordinates |
| 1 | Exact starting point from survey-based coordinates |

### Questions and issues

* If this is a binary field, should we model with a simple ```exactPointOfOrigin``` true/false field?

* How does this relate to the IATI location [exactness](http://iatistandard.org/202/codelists/GeographicExactness/) concept and codes?

## General feedback

General feedback on this proposal is welcome

**Comment by hrdwm14** [comment]
Hi Tim:

Thanks for your thoughtful questions about the specification - the authors and I have brainstormed initial answers, found below. We look forward to discussing this in greater depth. 

Best,
Harsh Desai

============

> - In OCDS we usually work with camelCase rather than numeric codelist values. Is there a strong reason to prefer numeric values here?

When writing this specification, we referred to the 'precision code' schema in AidData's existing methodology for geocoding aid projects, which assigns numeric codes to different location categories. A numeric code list is not strictly necessary for this specification, especially if the OCDS reverts to camelCase, although we have found numeric values in this case to be more user-friendly and interpretable by academic and policy researchers. A potential alternative schema that incorporates camelCase values could be as follows (note: these values can also be truncated if they are too long for the code, as written):

| Value  | Category |
| ------------- | ------------- |
| spatialData  | The polygon is sourced from spatial (digitized) information published by a company, government, or third-party institution.|
| decimalCoordinates  | The polygon is sourced from location information that provides decimal degrees for all vertices of the polygon. | 
| utmCoordinates | The polygon is sourced from location information that provides UTM coordinates for all vertices of the polygon.|
| surveyCoordinatesAll | The polygon is sourced from survey-based coordinates that provide the location of all vertices of the polygon. |
| surveyCoordinatesVaried| The polygon is sourced from survey-based coordinates that do not provide the location of all vertices of the polygon.|
| coordinatesVaried| The location information for a given polygon varies across vertices among the categories presented above.|
 
> What other standardised methods for polygon provenance exist that we might draw upon?

After searching existing open-source land registries and cadastral databases, we have not encountered other methods of polygon provenance for open contracting data that would serve the same purpose as the proposed property. However, we welcome drawing upon existing initiatives rather than creating an entirely new categorization. We believe that this code list is uniquely important to the challenges of geocoding and standardizing location information reported in contracts (namely, concession contracts, but we believe that it has broader applicability).

> Where in the location extension structure should this information be held?

Given the assumptions in the specification (that this property applies to polygons, and that polygons exhibit a one-to-one relationship with a contract ID), we believe that it should be an additional property under 'items'.

> If this is a binary field, should we model with a simple exactPointOfOrigin true/false field?

Yes, a true/false field would make sense.

> How does this relate to the IATI location exactness concept and codes?

We modeled this property after the IATI geographic exactness field. In IATI, this field provides a meaningful indicator of the accuracy and reliability of a given point (i.e. aid project). We believe that this measure is meaningful for open contracting data in the case of the exactness of the starting point, which affects all subsequent vertices in a polygon. In future extensions, we can consider applying this code to every vertex of a polygon to enable users to gauge the true extent of spatial imprecision inherent in the polygon; however, at this stage, we believe that the proposed property is a meaningful first step.

**Comment by timgdavies** [comment]
We had a good call with the AidData team around this (thanks!), and discussed:

* Capturing examples of each of the kinds of geodata source above to give publishers and users clearer intuitive sense of them;
* Considering making ```sourceType``` an array of tags that can be combined to indicate different aspects of the source from which location information is derived;
* Considering a ```sourceURI``` for linking out to original source information

Next steps are to:

* Investigate and test how a tagging approach would work;
* Look for precedents from other standards for appropriate tags;
* Talk to others collecting geodata on concessions;

**Comment by jpmckinney** [comment]
Moved https://github.com/open-contracting/ocds-extensions/issues/10
